name: Realease

on:
  release:
    types: [published]

jobs:
  build:
    name: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependences
        run: bun install

      - name: build
        run: bun run build

      - name: zip releases
        run: |
          mkdir -p "dist/zips"
          for file in dist/*; do
            if [ -f $file ]; then
              filename=$(basename "$file")
              7z a "dist/zips/$filename.zip" "$file" LICENSE README.md
            fi
          done

      - name: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/zips/*
          token: ${{ secrets.GITHUB_TOKEN }}
